# Name of this GitHub Actions workflow.
name: Semgrep

on:
  # on direct commit
  push:
    branches:
    - main
    - master
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 48 1 * * *

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - run: |
          apk update
          apk add openjdk17
          semgrep ci --supply-chain --allow-local-builds --debug
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          GRADLE_OPTS: >-
            -Dorg.gradle.daemon=false
            -Dorg.gradle.vfs.watch=false
            -Dorg.gradle.vfs.watch.useNative=false
            -Dorg.gradle.internal.launcher.watcher=false
            -Dorg.gradle.native=false
